### ISSUE TITLE
Device found but not connecting.

### ISSUE THREAD

**Issue by Enmud** [googlecast/CastHelloText-ios#10]
Hi I am using swift to develop an app which has chrome cast feature. I am suing the code from this project(ViewController.swift). I can see that device is found from the logs but device manager is not able to detect the devices. Please find below logs. I am using normal button instead of UINavigationItem(not using UINavigationController).

2016-08-17 00:01:40.875 APPName [766:229387] GoogleCast framework version 3.1.1.10003
-[GCKNNetworkReachability startMonitoring] - startMonitoring
-[GCKEventLogger logDeviceScanCriteriaChanged:] - LOG EVENT: DeviceScanCriteriaChanged session=(null)
-[GCKEventLogger logDeviceScanStarted:] - LOG EVENT: DeviceScanStarted session=<0x166b3200:GCKDiscoveryLoggingSession> 1, 1471372301447, 6c:72:20:fa:6d:50
-[GCKClearcutLogger logEvent:fromSource:] - logging an event from source: 67
-[GCKCastDeviceBonjourScanner startScanWithSubtypes:] - Starting Bonjour scan for subtypes: {(
    "_CC1AD845"
)}
__41-[GCKClearcutLogger logEvent:fromSource:]_block_invoke - opening new log file in: /var/mobile/Containers/Data/Application/D069AB96-043A-4F08-930A-748FD29A1BCA/Library/Caches/GCKClearcutLogger/67/2016.08.17.00.01.41.450
-[GCKClearcutLogWriter open] - opened log file: /var/mobile/Containers/Data/Application/D069AB96-043A-4F08-930A-748FD29A1BCA/Library/Caches/GCKClearcutLogger/67/2016.08.17.00.01.41.450
-[GCKCastDeviceBonjourScanner netServiceBrowser:didFindService:moreComing:] - found ChromeCastDeviceFriendlyName,(null)
-[GCKCastDeviceBonjourScanner startResolveForEntry:] - resolving ChromeCastDeviceFriendlyName
-[GCKCastDeviceBonjourScanner netServiceBrowser:didFindService:moreComing:] - found ChromeCastDeviceFriendlyName,_CC1AD845
-[GCKEventLogger logMdnsSubtypeFilteringEvent:session:subtype:isPositiveFilteringResult:wasSubtypePreviouslyDiscovered:latency:] - LOG EVENT: device=<0x16568140:GCKDevice> [com.google.cast.CastDevice] 'ChromeCastDeviceFriendlyName' 192.168.0.123:8009 (386caabaf1d43746710b8d8c492ab7af), session=<0x166b3200:GCKDiscoveryLoggingSession> 1, 1471372301447, 6c:72:20:fa:6d:50, subtype=_CC1AD845, isPositiveFilteringResult=1, wasSubtypePreviouslyDiscovered=0, latency=0.059887
-[GCKClearcutLogger logEvent:fromSource:] - logging an event from source: 67
-[GCKDeviceScanner deviceProvider:didPublishDevice:] - device online: <0x16568140:GCKDevice> [com.google.cast.CastDevice] 'ChromeCastDeviceFriendlyName' 192.168.0.123:8009 (386caabaf1d43746710b8d8c492ab7af)
Device found: Optional("ChromeCastDeviceFriendlyName")
nil
-[GCKEventLogger logDeviceDiscovered:session:] - LOG EVENT: device=<0x16568140:GCKDevice> [com.google.cast.CastDevice] 'ChromeCastDeviceFriendlyName' 192.168.0.123:8009 (386caabaf1d43746710b8d8c492ab7af), session=<0x166b3200:GCKDiscoveryLoggingSession> 1, 1471372301447, 6c:72:20:fa:6d:50
-[GCKClearcutLogger logEvent:fromSource:] - logging an event from source: 67
-[GCKEventLogger logPublishedDevices:session:] - LOG EVENT: PublishedDevices session=<0x166b3200:GCKDiscoveryLoggingSession> 1, 1471372301447, 6c:72:20:fa:6d:50
-[GCKClearcutLogger logEvent:fromSource:] - logging an event from source: 67
-[GCKCastDeviceBonjourScanner netServiceBrowser:didFindService:moreComing:] - found ChromeCastDeviceFriendlyName,(null)
-[GCKCastDeviceBonjourScanner netServiceBrowser:didFindService:moreComing:] - found ChromeCastDeviceFriendlyName,_CC1AD845
-[GCKCastDeviceBonjourScanner netServiceBrowser:didFindService:moreComing:] - found ChromeCastDeviceFriendlyName,(null)
-[GCKCastDeviceBonjourScanner netServiceBrowser:didFindService:moreComing:] - found ChromeCastDeviceFriendlyName,_CC1AD845.

Thanks in advance.

**Comment by entertailion** [comment]
There are various improvements and bug fixes in the Cast SDK v3 release. We recommend that you use the new SDK instead which includes widgets for the Cast button and device list.
