### ISSUE TITLE
How can I use GCKUICastButton?

### ISSUE THREAD

**Issue by billypchan** [googlecast/CastHelloText-ios#12]
Hello! 
I am trying to create a  button in viewDidLoad():
let castButton = GCKUICastButton(frame: CGRect(x: CGFloat(0), y: CGFloat(0), width: CGFloat(24), height: CGFloat(24)))

But I got this error:
.../CastHelloText-ios/HelloTextGoogleCastSwift/ViewController.swift:65:26: Use of unresolved identifier 'GCKUICastButton'

Do I need additional steps to use the cast button? Thanks!

**Comment by entertailion** [comment]
Are you using Cocoapods?

**Comment by billypchan** [comment]
Hello entertailion, yes, I am use cocoapod. Here is the podfile:

use_frameworks!

target 'HelloTextGoogleCastSwift' do
  pod 'google-cast-sdk'
end

**Comment by entertailion** [comment]
Please use the last Cast SDK which includes various Cast widgets.
