### ISSUE TITLE
App crashes after GCKDeviceManager.connect() when connecting to "Nearby device"

### ISSUE THREAD

**Issue by billypchan** [googlecast/CastHelloText-ios#13]
Hello,
In my wifi network there are no Chromecasts online but there is still a "Nearby device" in the list. When I select that device and it crashes at Queue: com.apple.root.default-qos (concurrent) after this line:

        deviceManager!.connect()

I retry with a Android phone in the same wifi network, it also shows the "Nearby device" and it ask for PIN after I select that device, but it staying in connecting state for a long time and nothing happens.

**Comment by billypchan** [comment]
I find the solution. The reason is missing permission for microphone. Added this in info.plist:

<key>NSMicrophoneUsageDescription</key>
<string>For Chromecast PIN entering!</string>

**Comment by entertailion** [comment]
It is covered by the Cast docs: https://developers.google.com/cast/docs/guest_mode#ios-bluetooth-and-microphone-permissions

**Comment by billypchan** [comment]
Thanks entertailion!
