### ISSUE TITLE
receiver.html URL 404s

### ISSUE THREAD

**Issue by ImJasonH** [googlecast/CastHelloText-ios#4]
https://b1c41147cac62334751b00bb7fea03a9ecdcc182.googledrive.com/host/0B716ywBKT84AMXBENXlnYmJISlE/GoogleDriveHosting.html 404s for me, did the file move?

If it's just meant to be an example Drive URL, maybe a more obviously sample URL would make that clearer.

**Comment by chrisrecher** [comment]
Link no longer present in README, closing.
