### ISSUE TITLE
Making this app UX Checklist compliant

### ISSUE THREAD

**Issue by grantkemp** [googlecast/CastHelloText-ios#5]
Hi Guys, 

I have implemented a similar flow with my IOS app and now have it working great with Google Cast. 

The problem is that before I put it to the appstore,  I need to make it UX Checklist compliant which I have spend the last 3 days working on without success.  

Is there a list of the minimum changes that we need to do to make it compliant ( preferably with some sample code)

**Comment by entertailion** [comment]
You can take a look at our iOS reference app which is UX compliant: https://github.com/googlecast/CastVideos-ios

**Comment by chrisrecher** [comment]
This sample app intentionally is not UX Checklist compliant for simplicity's sake. As mentioned, https://github.com/googlecast/CastVideos-ios shows UX Checklist compliance.
